---
- name: Debian - Set extra user groups
  when: item.value.state is defined and item.value.groups.Debian is defined
  user:
    name: "{{ item.value.username }}"
    groups: "{{ item.value.groups.Debian }}"
  with_dict: "{{ aspects_local_users }}"
  tags:
    - aspects_local_users
    - aspects_local_users_groups
